services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'America/Lima'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8'
      PGCLIENTENCODING: 'UTF8'
    container_name: nexus_db
    command: postgres -c 'client_encoding=UTF8'
    volumes:
      - ./postgres:/var/lib/postgresql/data
