services:
  nexusapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: nexus-docker
    container_name: nexusapp
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT = ${PORT}
      - JWT_SECRET = ${JWT_SECRET}
      - JWT_REFRESH_SECRET = ${JWT_REFRESH_SECRET}
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY = ${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET = ${CLOUDINARY_API_SECRET}
      - DB_PASSWORD = ${DB_PASSWORD}
      - DB_NAME = ${DB_NAME}
      - DB_HOST = ${DB_HOST}
      - DB_PORT = ${DB_PORT}
      - DB_USERNAME = ${DB_USERNAME}

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_DB: ${DB_NAME}
      - TZ: 'America/Lima'
